# Generated by Django 3.2 on 2021-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_vids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
