# Generated by Django 3.2 on 2021-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredited_assesors', '0002_auto_20210612_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sex', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='accredited_assesors',
            name='Sex',
        ),
        migrations.AddField(
            model_name='accredited_assesors',
            name='Sex',
            field=models.ManyToManyField(to='accredited_assesors.Gender'),
        ),
    ]
