# Generated by Django 3.2 on 2021-06-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accredited_assesors', '0003_auto_20210612_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='accredited_assesors',
            name='Institution',
        ),
        migrations.AddField(
            model_name='accredited_assesors',
            name='Institution',
            field=models.ManyToManyField(to='accredited_assesors.Center'),
        ),
    ]
