# Generated by Django 3.2 on 2021-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='headlines',
            field=models.BooleanField(default=True),
        ),
    ]
