# Generated by Django 3.2 on 2021-06-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EGACE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(max_length=100)),
                ('enrolled', models.IntegerField()),
                ('perc_enrolled', models.IntegerField()),
                ('graduate', models.IntegerField()),
                ('perc_graduate', models.IntegerField()),
                ('assessed', models.IntegerField()),
                ('perc_assessed', models.IntegerField()),
                ('certified', models.IntegerField()),
                ('perc_certified', models.IntegerField()),
                ('employed', models.IntegerField()),
                ('perc_employed', models.IntegerField()),
                ('date_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
