# Generated by Django 3.2 on 2021-06-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EGACE', '0002_auto_20210613_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EGACE',
            new_name='models_EGACE',
        ),
    ]
