# Generated by Django 3.2 on 2021-06-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EGACE', '0003_rename_egace_models_egace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='models_EGACE',
            new_name='egace',
        ),
    ]
