# Generated by Django 3.2 on 2021-05-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='philgeps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('project', models.TextField()),
                ('invitation', models.FileField(upload_to='')),
                ('notice_of_award', models.FileField(upload_to='')),
                ('approve_contract', models.FileField(upload_to='')),
                ('notice_to_proceed', models.FileField(upload_to='')),
                ('remarks', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ManyToManyField(to='philgeps.suppliers')),
            ],
        ),
    ]
