# Generated by Django 3.2 on 2021-05-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philgeps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='philgeps',
            new_name='philG',
        ),
    ]
