# Generated by Django 3.2 on 2021-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philgeps', '0005_alter_philg_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philg',
            name='approve_contract',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='philg',
            name='invitation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='philg',
            name='notice_of_award',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='philg',
            name='notice_to_proceed',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
