# Generated by Django 3.2 on 2021-04-25 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_auto_20210425_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifications',
            name='code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
