# Generated by Django 3.2 on 2021-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NCHolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('extname', models.CharField(max_length=100)),
                ('certType', models.CharField(max_length=100)),
                ('NCTitle', models.TextField()),
                ('COCTitle', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('date_released', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
