# Generated by Django 3.2 on 2021-06-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NC_holders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncholders',
            name='picture',
        ),
    ]
