# Generated by Django 3.2 on 2021-06-13 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NC_holders', '0003_auto_20210613_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncholders',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
