# Generated by Django 3.2 on 2021-06-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NC_holders', '0004_ncholders_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncholders',
            name='picture',
        ),
    ]
