# Generated by Django 3.2 on 2021-06-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='caption',
        ),
    ]
