# Generated by Django 3.2 on 2021-06-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0002_remove_stories_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='name',
            new_name='title',
        ),
    ]
