# Generated by Django 3.2 on 2021-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0004_auto_20210616_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='caption',
            field=models.TextField(),
        ),
    ]
