# Generated by Django 3.2 on 2021-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_qualifications_code'),
        ('nttc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nttc',
            name='school',
            field=models.ManyToManyField(to='centers.Qualifications'),
        ),
    ]
