# Generated by Django 3.2 on 2021-04-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nttc', '0002_nttc_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nttc',
            old_name='school',
            new_name='qualification',
        ),
    ]
