# Generated by Django 3.2 on 2021-04-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nttc', '0003_rename_school_nttc_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nttc',
            name='date_released',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nttc',
            name='expiration',
            field=models.DateField(),
        ),
    ]
